project:
  type: website

website:
  title: "Cuong Nguyen"
  description: "Probabilistic machine learning"
  navbar:
    title: ""
    background: light
    search: true
    right:
      - icon: pencil-square
        text: Blog
        file: blog.qmd
      - icon: easel
        text: Teaching
        file: teaching.qmd
      - icon: person-circle
        text: About
        file: about.qmd
      # - text: "More"
      #   menu:
      #     - teaching.qmd
      #     - publication.qmd
  back-to-top-navigation: true
  google-analytics:
    tracking-id: G-NLRVZL0JSR
    version: 4
  site-url: https://cnguyen10.github.io

format:
  html:
    toc: false
    lightbox: true
    mainfont: Arial, sans-serif
    html-math-method: katex
    number-sections: true
    anchor-sections: true
    css: styles.css
    include-in-header:
      text: ''
    citations-hover: true
    footnotes-hover: true
    linkcolor: "#006400"

filters:
  - pseudocode

execute:
  freeze: auto
