project:
  type: website

website:
  title: "Cuong Nguyen"
  favicon: robot.svg
  twitter-card: true
  navbar:
    background: light
    search: true
    right:
      - icon: pencil-square
        text: Blog
        file:  blog.qmd
      - icon: person-circle
        text: About
        file: about.qmd
      # - icon: github
      #   href: https://github.com/cnguyen10
      # - icon: twitter
      #   href: https://twitter.com/cuongcn10
  google-analytics: G-NLRVZL0JSR

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-expand: true
    html-math-method: katex
    number-sections: true
    anchor-sections: true
    css: styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.css">
        <script src="https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.js"></script>
        <script>
          window.onload = async function() {
            var options = {
              indentSize: '1.2em',
              commentDelimiter: '\u00A0\u00A0\u00A0\u00A0\u00A0 \u25B9 \u0020',
              lineNumber: true,
              lineNumberPunc: ':',
              noEnd: false,
              captionCount: undefined
            };
            pseudocode.renderClass("pseudocode", options);
          }
        </script>

execute:
  freeze: auto
