---
title: "About"
image: https://avatars.githubusercontent.com/u/15698019
about:
  template: solana
  image-shape: round
  image-width: 10em
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/cuongcn10
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/cuong-c-nguyen
    - icon: github
      text: Github
      href: https://github.com/cnguyen10
    - icon: mortarboard-fill
      text: Google Scholar
      href: https://scholar.google.com.au/citations?user=eAkq43kAAAAJ
    - icon: envelope-at
      text: Email
      href: mailto:cuong@aiml.team
format:
  html:
    toc: false
    number-sections: false
---

I am a Mechanical Engineer turn into a Machine Learning researcher. My interest is on the mathematical modelling and theoretical analysis to gain insights into the problems of interest. Before getting into the academic career, I worked as a Process and Equipment Engineer at Intel Products Vietnam for three years.

Beside my academic life, I have a simple life as a country guy coming from a small town in the South of Vietname, where the Mekong river flows out to the South China Sea. It has a complex river system which provides illuvi to plant different kinds of fruit-trees.

### Education
**University of Adelaide**,  South Australia, AU\
<span class="bi bi-mortarboard-fill"></span> <span class="bi bi-laptop"></span> <em>PhD in Computer Science</em>\
April 2018 - March 2022

**University of Adelaide**, South Australia, AU\
<span class="bi bi-mortarboard-fill"></span> <span class="bi bi-cpu"></span> <em>MPhil. in Electronics Engineering</em>\
Aug 2015 - Jan 2018

**Portland State University**, Oregon, US\
<span class="bi bi-mortarboard-fill"></span> <span class="bi bi-wrench-adjustable"></span> <em>B.S. in Mechanical Engineering</em>\
Jul 2011 - June 2012